### ISSUE TITLE
Huge memory footprint?

### ISSUE THREAD

**Issue by jon-weisz** [PR2/rqt_pr2_dashboard#3] opened 2013-01-20 23:27 UTC
Running rqt_pr2_dashboard overnight on PR-N took up all of the memory on my machine. I don't know if this is a leak or a problem in the design.

![Screenshot from 2013-01-20 15:14:19](https://f.cloud.github.com/assets/2566558/81755/d3b0cbd8-6358-11e2-8415-4f05f044d621.png)

**Comment by 130s** [comment] 2013-01-20 23:31
@jon-weisz were you using monitor (device tree that shows warning & error status, which is `rqt_robot_monitor` internally used) on? 

If so, I'll check to see if that happens with `rqt_robot_monitor` standalone.

**Comment by jon-weisz** [comment] 2013-01-20 23:37
I believe I was.

**Comment by 130s** [comment] 2013-01-21 09:48
@jon-weisz after running `rqt_robot_monitor` separately for 4 hrs without any manual operation, I've seen only 1 Mb increase so far (from 105 Mb to 106). I'll keep it running but do you remember any operation you did on `rqt_robot_monitor` (ie. device trees, timeline)?

**Comment by jon-weisz** [comment] 2013-01-21 11:02
Hey Isaac,
I did rosrun rqt_pr2_dashboard rqt_pr2_dashboard and then clicked the
leftmost button at the top, which I think is the monitor button? I'll leave
it running again tonight and get back to you.

--Jon

**Comment by jon-weisz** [comment] 2013-01-21 18:33
Hey Isaac,
I was not able to reproduce the memory leak, so I'm not sure what's going
on. I'll let you know if I ever see it again.

--Jon

**Comment by 130s** [comment] 2013-01-21 19:53
I'll also keep watching this issue. I kept pr2_dashboard running overnight but found no memory increase.

Next time you see the issue, can you give us memory usage by something like:

```
rosuser@btt:~/ROS$ ps awx |grep rqt
 9394 pts/1    Sl     7:05 python ~/ROS/groovy_quantal/catkin_ws/devel/bin/rqt
11602 pts/1    S+     0:00 grep --color=auto rqt
rosuser@btt:~/ROS$ pmap -x 9394
```

`pmap` takes `pid` as an arg, and it gives memory usage per thread? I haven't been fully clear yet but it's better to record in detail like this, and it's commanline I/F. No need to take snapshot. I uploaded example output here http://pastebin.com/ahV2tVJP

I see the version of modules you're using:

```
ros-groovy-rqt-pr2-dashboard 0.2.3-s1358646422~precise
ros-groovy-rqt 0.2.8-0precise-20130119-2037-+0000
ros-groovy-rqt-common-plugins 0.2.9-0precise-20130120-0023-+0000
ros-groovy-rqt-robot-plugins 0.2.8-0precise-20130119-2351-+0000
ros-groovy-qt-gui-core 0.2.12-0precise-20130119-2029-+0000
```

**Comment by ablasdel** [comment] 2013-01-25 23:27
@jon-weisz Have you gotten anywhere on a process to reproduce this issue?

**Comment by jon-weisz** [comment] 2013-01-25 23:38
I saved the output of pmap the last time it happened, but other than that,
no.

--Jon

**Comment by ahendrix** [comment] 2013-01-25 23:54
I'm seeing this as well, after running the dashboard for a few hours.

From top:
 4212 ahendrix  20   0 1488m 190m  65m S    1  1.2  31:57.20 rqt                            

pmap output: http://pastebin.com/n4PmmxBi

**Comment by ablasdel** [comment] 2013-01-26 00:18
When you have an instance of this issue please try closing the
robot_monitor.
Post here if it has any noticeable effect. This should narrow down my hunt.

also the number of messages you currently have in the console in addition
to the rough rate that they are coming in would be useful.

**Comment by ahendrix** [comment] 2013-01-26 01:09
When this happens, I see two problems: high CPU usage and high memory usage.

Closing robot_monitor reduces the CPU load from 120%+ to a more reasonable 1-10%, but doesn't reduce the memory usage.

I have roughly 2000 messages in the console.

**Comment by ahendrix** [comment] 2013-01-26 01:12
It looks like the CPU usage climbs the longer robot_monitor is running; in particular it climbs from 1% with robot_monitor closed to ~90% after robot_monitor has been running for roughly 5 minutes.

**Comment by 130s** [comment] 2013-01-26 02:01
Ok now 2 different phenomenon...memory and CPU.

If possible, when either one/both happen, can you also take a snapshot of `pr2_dashboard`?

@ahendrix what operations do you do after opening robot_monitor?

**Comment by 130s** [comment] 2013-02-04 20:05
Just a status update. Still isolation phase. @ahendrix will try to use `rqt_robot_monitor` separate from `rqt_pr2_dashboard` once his PR2 is back. 

Over the weekend I kept rqt_robot_monitor running and there's not even a single mega byte of memory increase.

rqt_pr2_dashboard 190aa79c3ae28f3d37bc32b974c36635144cf1f9, rqt_robot_monitor 9591ce8461c920e5b52e10bc535506516817db6d

**Comment by ahendrix** [comment] 2013-02-04 23:53
Confirmed; I'm not seeing a big memory leak in robot_monitor either.

Starting memory: 135m/1138m @ Mon Feb  4 14:14:04 PST 2013
After starting the PR2: 162m/1210m @ Mon Feb  4 14:16:59 PST 2013
Ending memory: 164m/1210m @ Mon Feb  4 15:52:06 PST 2013

**Comment by ablasdel** [comment] 2013-08-02 20:13
Where are we on this one? are we still seeing unreasonable memory usage in the dashboard?

**Comment by ahendrix** [comment] 2013-08-02 21:21
I'm pretty sure this was fixed.

**Comment by ablasdel** [comment] 2013-08-02 21:25
I think so too. I will close this and if it shows up we can re-open it.

**Closed as completed by ablasdel** 2013-08-02 21:25 UTC
