### ISSUE TITLE
Diagnostics icon gets stuck in stale state

### ISSUE THREAD

**Issue by ahendrix** [PR2/rqt_pr2_dashboard#7] opened 2013-01-30 00:12 UTC
When running the dashboard, the diagnostics icon sometimes gets stuck in the "stale" state. In particular, this only appears to affect the transistion from a stale state to an error state, as when the diagnostics start up in an error state.

To reproduce:
start a roscore on the PR2
start rqt_pr2_dashboard on the desktop; open a robot_monitor
wait for the dashboard to register as stale
roslaunch /etc/ros/robot.launch on the PR2
observe that the diagnostics icon remains stale as long as the diagnostic state is error

**Comment by ablasdel** [comment] 2013-02-08 01:57
fixed by https://github.com/ros-visualization/rqt_robot_plugins/commit/572283a983c8599b19741ac3caa17039171364da

Was unable to reproduce but I think I found the logic hole it was falling into and patched it up. If you see it again please reopen.

**Closed as completed by ablasdel** 2013-02-08 01:57 UTC
